// <auto-generated />
using System;
using AirlineBookingSystem.Flights.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineBookingSystem.Flights.Infrastructure.Migrations
{
    [DbContext(typeof(FlightsDbContext))]
    partial class FlightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("AirlineBookingSystem.Flights.Core.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            PassengerName = "John Smith",
                            PassportNumber = "BX534916732",
                            SeatNumber = "12C",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 3,
                            PassengerName = "Alice Thompson",
                            PassportNumber = "AX128374950",
                            SeatNumber = "14A",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 5,
                            PassengerName = "Liam Johnson",
                            PassportNumber = "CT938471205",
                            SeatNumber = "22F",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 1,
                            PassengerName = "Emma Wilson",
                            PassportNumber = "PL372849172",
                            SeatNumber = "8B",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 7,
                            PassengerName = "Noah Brown",
                            PassportNumber = "YX182736459",
                            SeatNumber = "16C",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 2,
                            PassengerName = "Olivia Davis",
                            PassportNumber = "RB273648159",
                            SeatNumber = "10A",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 4,
                            PassengerName = "James Taylor",
                            PassportNumber = "QP394857612",
                            SeatNumber = "9E",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 6,
                            PassengerName = "Sophia Martinez",
                            PassportNumber = "KM837261945",
                            SeatNumber = "19D",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 9,
                            PassengerName = "Benjamin Lee",
                            PassportNumber = "UT928374560",
                            SeatNumber = "13B",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 10,
                            PassengerName = "Isabella White",
                            PassportNumber = "DZ173849260",
                            SeatNumber = "21A",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 11,
                            FlightId = 2,
                            PassengerName = "Lucas Harris",
                            PassportNumber = "WL294837165",
                            SeatNumber = "12D",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 12,
                            FlightId = 8,
                            PassengerName = "Mia Clark",
                            PassportNumber = "GX193847205",
                            SeatNumber = "23C",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 13,
                            FlightId = 5,
                            PassengerName = "Henry Young",
                            PassportNumber = "JF384726195",
                            SeatNumber = "7F",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 14,
                            FlightId = 3,
                            PassengerName = "Charlotte Allen",
                            PassportNumber = "MB837261934",
                            SeatNumber = "15E",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 15,
                            FlightId = 11,
                            PassengerName = "Alexander Scott",
                            PassportNumber = "ER918374612",
                            SeatNumber = "18B",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 16,
                            FlightId = 14,
                            PassengerName = "Amelia King",
                            PassportNumber = "PK183746205",
                            SeatNumber = "5C",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 17,
                            FlightId = 6,
                            PassengerName = "Daniel Green",
                            PassportNumber = "ZH827364920",
                            SeatNumber = "6D",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 18,
                            FlightId = 12,
                            PassengerName = "Evelyn Hall",
                            PassportNumber = "NL728394651",
                            SeatNumber = "17A",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 19,
                            FlightId = 13,
                            PassengerName = "Matthew Baker",
                            PassportNumber = "LS283746159",
                            SeatNumber = "24F",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 20,
                            FlightId = 10,
                            PassengerName = "Harper Nelson",
                            PassportNumber = "CV837465120",
                            SeatNumber = "20E",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 21,
                            FlightId = 4,
                            PassengerName = "Jackson Adams",
                            PassportNumber = "HT918374621",
                            SeatNumber = "3A",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 22,
                            FlightId = 7,
                            PassengerName = "Abigail Rivera",
                            PassportNumber = "UV837162930",
                            SeatNumber = "4B",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 23,
                            FlightId = 9,
                            PassengerName = "Sebastian Ramirez",
                            PassportNumber = "YX847261950",
                            SeatNumber = "2F",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 24,
                            FlightId = 8,
                            PassengerName = "Emily Perez",
                            PassportNumber = "KG837261940",
                            SeatNumber = "11C",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 25,
                            FlightId = 1,
                            PassengerName = "Aiden Carter",
                            PassportNumber = "NE102938475",
                            SeatNumber = "6E",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 26,
                            FlightId = 13,
                            PassengerName = "Ella Roberts",
                            PassportNumber = "RH837261953",
                            SeatNumber = "1D",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 27,
                            FlightId = 12,
                            PassengerName = "Logan Mitchell",
                            PassportNumber = "FE918374625",
                            SeatNumber = "7C",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 28,
                            FlightId = 15,
                            PassengerName = "Scarlett Turner",
                            PassportNumber = "OB374829105",
                            SeatNumber = "8F",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 29,
                            FlightId = 6,
                            PassengerName = "David Phillips",
                            PassportNumber = "MT837261970",
                            SeatNumber = "5A",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 30,
                            FlightId = 11,
                            PassengerName = "Grace Campbell",
                            PassportNumber = "EQ193847205",
                            SeatNumber = "9B",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 31,
                            FlightId = 14,
                            PassengerName = "Joseph Parker",
                            PassportNumber = "RE827364920",
                            SeatNumber = "10F",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 32,
                            FlightId = 5,
                            PassengerName = "Chloe Evans",
                            PassportNumber = "SU837261984",
                            SeatNumber = "13A",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 33,
                            FlightId = 2,
                            PassengerName = "Samuel Edwards",
                            PassportNumber = "TK273849162",
                            SeatNumber = "17F",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 34,
                            FlightId = 3,
                            PassengerName = "Aria Collins",
                            PassportNumber = "VC837261918",
                            SeatNumber = "18C",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 35,
                            FlightId = 15,
                            PassengerName = "Elijah Stewart",
                            PassportNumber = "BG837261933",
                            SeatNumber = "14E",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 36,
                            FlightId = 7,
                            PassengerName = "Victoria Sanchez",
                            PassportNumber = "ZH837261911",
                            SeatNumber = "22C",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 37,
                            FlightId = 9,
                            PassengerName = "Wyatt Morris",
                            PassportNumber = "DE283746195",
                            SeatNumber = "19B",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 38,
                            FlightId = 6,
                            PassengerName = "Zoey Rogers",
                            PassportNumber = "XM837261997",
                            SeatNumber = "15A",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 39,
                            FlightId = 8,
                            PassengerName = "Gabriel Reed",
                            PassportNumber = "PY837261934",
                            SeatNumber = "16F",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 40,
                            FlightId = 10,
                            PassengerName = "Lily Cook",
                            PassportNumber = "TR827364928",
                            SeatNumber = "12B",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("AirlineBookingSystem.Flights.Core.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalAirportCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureAirportCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AircraftType = "Boeing 737-800",
                            Arrival = new DateTime(2025, 10, 12, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "BUD",
                            Departure = new DateTime(2025, 10, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "OSL",
                            FlightCode = "DY1550",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 2,
                            AircraftType = "Airbus A320",
                            Arrival = new DateTime(2025, 10, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "AMS",
                            Departure = new DateTime(2025, 10, 13, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "FRA",
                            FlightCode = "LH2021",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 3,
                            AircraftType = "Airbus A321",
                            Arrival = new DateTime(2025, 11, 1, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "MAD",
                            Departure = new DateTime(2025, 11, 1, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "CDG",
                            FlightCode = "AF1133",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 4,
                            AircraftType = "Boeing 777",
                            Arrival = new DateTime(2025, 11, 5, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "ARN",
                            Departure = new DateTime(2025, 11, 5, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "LHR",
                            FlightCode = "BA804",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 5,
                            AircraftType = "Airbus A220",
                            Arrival = new DateTime(2025, 10, 20, 13, 40, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "CPH",
                            Departure = new DateTime(2025, 10, 20, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "OSL",
                            FlightCode = "SK1502",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 6,
                            AircraftType = "Embraer 190",
                            Arrival = new DateTime(2025, 11, 8, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "MUC",
                            Departure = new DateTime(2025, 11, 8, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "HEL",
                            FlightCode = "AY432",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 7,
                            AircraftType = "Boeing 737 MAX 8",
                            Arrival = new DateTime(2025, 12, 3, 0, 30, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "FCO",
                            Departure = new DateTime(2025, 12, 2, 21, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "IST",
                            FlightCode = "TK1891",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 8,
                            AircraftType = "Embraer 175",
                            Arrival = new DateTime(2025, 10, 27, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "OSL",
                            Departure = new DateTime(2025, 10, 27, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "AMS",
                            FlightCode = "KLM1187",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 9,
                            AircraftType = "Airbus A321neo",
                            Arrival = new DateTime(2025, 11, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "LTN",
                            Departure = new DateTime(2025, 11, 3, 7, 10, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "BUD",
                            FlightCode = "W61302",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 10,
                            AircraftType = "Boeing 737-800",
                            Arrival = new DateTime(2025, 11, 10, 20, 10, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "ZRH",
                            Departure = new DateTime(2025, 11, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "WAW",
                            FlightCode = "LO285",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 11,
                            AircraftType = "Airbus A320",
                            Arrival = new DateTime(2025, 10, 30, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "LIS",
                            Departure = new DateTime(2025, 10, 30, 15, 50, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "BCN",
                            FlightCode = "IB3517",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 12,
                            AircraftType = "Airbus A319",
                            Arrival = new DateTime(2025, 12, 13, 0, 55, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "ATH",
                            Departure = new DateTime(2025, 12, 12, 22, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "FCO",
                            FlightCode = "AZ6051",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 13,
                            AircraftType = "Bombardier CS300",
                            Arrival = new DateTime(2025, 11, 14, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "VIE",
                            Departure = new DateTime(2025, 11, 14, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "ZRH",
                            FlightCode = "LX1624",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 14,
                            AircraftType = "Airbus A320neo",
                            Arrival = new DateTime(2025, 10, 31, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "FRA",
                            Departure = new DateTime(2025, 10, 31, 5, 55, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "LGW",
                            FlightCode = "EZY4283",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 15,
                            AircraftType = "Boeing 737-800",
                            Arrival = new DateTime(2025, 11, 18, 18, 40, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "CDG",
                            Departure = new DateTime(2025, 11, 18, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "OSL",
                            FlightCode = "DY1963",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("AirlineBookingSystem.Flights.Core.Models.Booking", b =>
                {
                    b.HasOne("AirlineBookingSystem.Flights.Core.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineBookingSystem.Flights.Core.Models.Flight", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
