// <auto-generated />
using System;
using AirlineBookingSystem.Flights.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineBookingSystem.Flights.API.Migrations
{
    [DbContext(typeof(FlightsDbContext))]
    [Migration("20250721120546_AddingBookingsTable")]
    partial class AddingBookingsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("AirlineBookingSystem.Flights.Core.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AirlineBookingSystem.Flights.Core.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalAirportCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureAirportCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AircraftType = "Boeing 737-800",
                            Arrival = new DateTime(2025, 10, 12, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "BUD",
                            Departure = new DateTime(2025, 10, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "OSL",
                            FlightCode = "DY1550",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 2,
                            AircraftType = "Airbus A320",
                            Arrival = new DateTime(2025, 10, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "AMS",
                            Departure = new DateTime(2025, 10, 13, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "FRA",
                            FlightCode = "LH2021",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 3,
                            AircraftType = "Airbus A321",
                            Arrival = new DateTime(2025, 11, 1, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "MAD",
                            Departure = new DateTime(2025, 11, 1, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "CDG",
                            FlightCode = "AF1133",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 4,
                            AircraftType = "Boeing 777",
                            Arrival = new DateTime(2025, 11, 5, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "ARN",
                            Departure = new DateTime(2025, 11, 5, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "LHR",
                            FlightCode = "BA804",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 5,
                            AircraftType = "Airbus A220",
                            Arrival = new DateTime(2025, 10, 20, 13, 40, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "CPH",
                            Departure = new DateTime(2025, 10, 20, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "OSL",
                            FlightCode = "SK1502",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 6,
                            AircraftType = "Embraer 190",
                            Arrival = new DateTime(2025, 11, 8, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "MUC",
                            Departure = new DateTime(2025, 11, 8, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "HEL",
                            FlightCode = "AY432",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 7,
                            AircraftType = "Boeing 737 MAX 8",
                            Arrival = new DateTime(2025, 12, 3, 0, 30, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "FCO",
                            Departure = new DateTime(2025, 12, 2, 21, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "IST",
                            FlightCode = "TK1891",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 8,
                            AircraftType = "Embraer 175",
                            Arrival = new DateTime(2025, 10, 27, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "OSL",
                            Departure = new DateTime(2025, 10, 27, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "AMS",
                            FlightCode = "KLM1187",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 9,
                            AircraftType = "Airbus A321neo",
                            Arrival = new DateTime(2025, 11, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "LTN",
                            Departure = new DateTime(2025, 11, 3, 7, 10, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "BUD",
                            FlightCode = "W61302",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 10,
                            AircraftType = "Boeing 737-800",
                            Arrival = new DateTime(2025, 11, 10, 20, 10, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "ZRH",
                            Departure = new DateTime(2025, 11, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "WAW",
                            FlightCode = "LO285",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 11,
                            AircraftType = "Airbus A320",
                            Arrival = new DateTime(2025, 10, 30, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "LIS",
                            Departure = new DateTime(2025, 10, 30, 15, 50, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "BCN",
                            FlightCode = "IB3517",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 12,
                            AircraftType = "Airbus A319",
                            Arrival = new DateTime(2025, 12, 13, 0, 55, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "ATH",
                            Departure = new DateTime(2025, 12, 12, 22, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "FCO",
                            FlightCode = "AZ6051",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 13,
                            AircraftType = "Bombardier CS300",
                            Arrival = new DateTime(2025, 11, 14, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "VIE",
                            Departure = new DateTime(2025, 11, 14, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "ZRH",
                            FlightCode = "LX1624",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 14,
                            AircraftType = "Airbus A320neo",
                            Arrival = new DateTime(2025, 10, 31, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "FRA",
                            Departure = new DateTime(2025, 10, 31, 5, 55, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "LGW",
                            FlightCode = "EZY4283",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 15,
                            AircraftType = "Boeing 737-800",
                            Arrival = new DateTime(2025, 11, 18, 18, 40, 0, 0, DateTimeKind.Unspecified),
                            ArrivalAirportCode = "CDG",
                            Departure = new DateTime(2025, 11, 18, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportCode = "OSL",
                            FlightCode = "DY1963",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("AirlineBookingSystem.Flights.Core.Models.Booking", b =>
                {
                    b.HasOne("AirlineBookingSystem.Flights.Core.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineBookingSystem.Flights.Core.Models.Flight", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
